-- AlterTable
ALTER TABLE "gold_loan_balance" ADD COLUMN     "balDaysToMature" INTEGER,
ADD COLUMN     "balPrinRcvd" DOUBLE PRECISION,
ADD COLUMN     "baseInterestDue" DOUBLE PRECISION,
ADD COLUMN     "branchCode" TEXT,
ADD COLUMN     "collExec" TEXT,
ADD COLUMN     "collExecCode" TEXT,
ADD COLUMN     "customerName" TEXT,
ADD COLUMN     "daysPostIntr" INTEGER,
ADD COLUMN     "deductions" DOUBLE PRECISION,
ADD COLUMN     "disbursedAmount" DOUBLE PRECISION,
ADD COLUMN     "discountAmt" DOUBLE PRECISION,
ADD COLUMN     "fullyReceived" TEXT,
ADD COLUMN     "grossWt" DOUBLE PRECISION,
ADD COLUMN     "intCollectedUpto" TIMESTAMP(3),
ADD COLUMN     "interestRcvDuring" DOUBLE PRECISION,
ADD COLUMN     "interestRcvd" DOUBLE PRECISION,
ADD COLUMN     "inventoryDate" TIMESTAMP(3),
ADD COLUMN     "inventoryNo" TEXT,
ADD COLUMN     "isLocked" TEXT,
ADD COLUMN     "isOnline" TEXT,
ADD COLUMN     "loanAvailedDays" INTEGER,
ADD COLUMN     "loanPeriod" INTEGER,
ADD COLUMN     "loanPeriodType" TEXT,
ADD COLUMN     "lockedBy" TEXT,
ADD COLUMN     "mktExec" TEXT,
ADD COLUMN     "mktExecCode" TEXT,
ADD COLUMN     "noticeLetter" TEXT,
ADD COLUMN     "openingBalance" DOUBLE PRECISION,
ADD COLUMN     "other1Due" DOUBLE PRECISION,
ADD COLUMN     "other2Due" DOUBLE PRECISION,
ADD COLUMN     "other3Due" DOUBLE PRECISION,
ADD COLUMN     "otherChargesDue" DOUBLE PRECISION,
ADD COLUMN     "partialPrinRcvd" DOUBLE PRECISION,
ADD COLUMN     "principalDr" DOUBLE PRECISION,
ADD COLUMN     "referenceNo" TEXT,
ADD COLUMN     "relExec" TEXT,
ADD COLUMN     "relExecCode" TEXT,
ADD COLUMN     "renewedFrom" TEXT,
ADD COLUMN     "reportDate" TIMESTAMP(3),
ADD COLUMN     "schemeCode" TEXT,
ADD COLUMN     "totalInterestDue" DOUBLE PRECISION,
ADD COLUMN     "uploadBatchId" TEXT;

-- AlterTable
ALTER TABLE "gold_loan_transaction" ADD COLUMN     "principalInterestReceived" DOUBLE PRECISION;

-- CreateTable
CREATE TABLE "upload_batches" (
    "id" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "portfolio" TEXT NOT NULL,
    "fileType" TEXT NOT NULL,
    "originalName" TEXT NOT NULL,
    "reportDate" TIMESTAMP(3),
    "uploadedBy" TEXT NOT NULL,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rowCount" INTEGER NOT NULL DEFAULT 0,
    "inserted" INTEGER NOT NULL DEFAULT 0,
    "updated" INTEGER NOT NULL DEFAULT 0,
    "errors" JSONB,

    CONSTRAINT "upload_batches_pkey" PRIMARY KEY ("id")
);
